import * as fs from 'fs/promises';
import * as path from 'path';
import { BaseInjector } from './base.js';
import type { AgentType, HandoffFormat } from '../types/index.js';

export class CursorInjector extends BaseInjector {
  readonly agent: AgentType = 'cursor';

  async inject(handoff: HandoffFormat): Promise<{ 
    success: boolean; 
    session_id?: string; 
    error?: string 
  }> {
    const validation = await this.validateHandoff(handoff);
    if (!validation.valid) {
      return {
        success: false,
        error: `Invalid handoff: ${validation.errors.join(', ')}`,
      };
    }

    try {
      // Cursor uses .cursor/rules for context injection
      // Create a rules file that can be imported
      const rulesContent = this.formatAsCursorRules(handoff);
      
      const cursorDir = path.join(handoff.metadata.project.path, '.cursor');
      await fs.mkdir(cursorDir, { recursive: true });
      
      const rulesFile = path.join(cursorDir, 'sync-ai-handoff.md');
      await fs.writeFile(rulesFile, rulesContent);

      // Also create a context file that can be manually referenced
      const contextFile = path.join(cursorDir, 'sync-ai-context.json');
      await fs.writeFile(contextFile, JSON.stringify(handoff, null, 2));

      return {
        success: true,
        session_id: `cursor-handoff-${Date.now()}`,
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error during injection',
      };
    }
  }

  private formatAsCursorRules(handoff: HandoffFormat): string {
    let content = `# Session Handoff Context\n\n`;
    content += `Transferred from ${handoff.metadata.source.agent} on ${handoff.metadata.source.timestamp}\n\n`;
    
    content += `## Current Goal\n`;
    content += `${handoff.summary.goal}\n\n`;
    
    content += `## Progress\n`;
    content += `- Status: ${handoff.summary.status}\n`;
    content += `- Completion: ${handoff.summary.progress_percentage}%\n`;
    content += `- Current Task: ${handoff.summary.current_task}\n\n`;

    if (handoff.summary.blockers && handoff.summary.blockers.length > 0) {
      content += `## Blockers\n`;
      handoff.summary.blockers.forEach((b: string) => {
        content += `- ${b}\n`;
      });
      content += '\n';
    }

    if (handoff.context.decisions.length > 0) {
      content += `## Key Decisions Made\n`;
      content += `Follow these decisions for consistency:\n\n`;
      handoff.context.decisions.forEach((d: { decision: string; rationale?: string; alternatives_considered: string[] }) => {
        content += `### ${d.decision}\n`;
        if (d.rationale) {
          content += `Rationale: ${d.rationale}\n`;
        }
        if (d.alternatives_considered.length > 0) {
          content += `Alternatives considered: ${d.alternatives_considered.join(', ')}\n`;
        }
        content += '\n';
      });
    }

    if (handoff.context.learnings.length > 0) {
      content += `## Learnings\n`;
      content += `Important discoveries from the previous session:\n\n`;
      handoff.context.learnings.forEach((l: string) => {
        content += `- ${l}\n`;
      });
      content += '\n';
    }

    if (handoff.context.assumptions.length > 0) {
      content += `## Assumptions\n`;
      content += `Working assumptions to maintain:\n\n`;
      handoff.context.assumptions.forEach((a: string) => {
        content += `- ${a}\n`;
      });
      content += '\n';
    }

    if (handoff.files.modified.length > 0 || handoff.files.created.length > 0) {
      content += `## Files Changed\n`;
      if (handoff.files.modified.length > 0) {
        content += `### Modified\n`;
        handoff.files.modified.forEach((f: { path: string; summary: string }) => {
          content += `- \`${f.path}\`: ${f.summary}\n`;
        });
        content += '\n';
      }
      if (handoff.files.created.length > 0) {
        content += `### Created\n`;
        handoff.files.created.forEach((f: string) => {
          content += `- \`${f}\`\n`;
        });
        content += '\n';
      }
    }

    if (handoff.continuation.files_to_focus.length > 0) {
      content += `## Files to Focus On\n`;
      content += `Start by reviewing these files:\n\n`;
handoff.continuation.files_to_focus.forEach((f: string) => {
      content += `- \`${f}\`\n`;
    });
      content += '\n';
    }

    content += `## Next Steps\n`;
    content += `${handoff.continuation.suggested_first_action}\n\n`;

    content += `---\n`;
    content += `*This context was generated by sync-ai handoff tool.*\n`;

    return content;
  }
}